accounts/urls.py
from django.urls import re_path
from django.contrib.auth import views as auth_views
from accounts import views as accounts_views

app_name = "accounts"
urlpatterns = [
    re_path(r'^signup/$', accounts_views.signup, name='signup'),
        ]

api/urls.py
from django.urls import re_path, include
from rest_framework import routers 
from api.views import NewsLetterView


router = routers.DefaultRouter()




urlpatterns = [
    re_path(r'^', include(router.urls)),
    re_path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    re_path(r'^newsletter/',NewsLetterView.as_view(), name = "subscribe"),

    
]

config/urls.py
from django.contrib import admin
from django.urls import re_path, include,path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views



urlpatterns = [
    # re_path(r'^', views.home),
    path(r'admin/', admin.site.urls),
    re_path(r'^accounts/', include('accounts.urls',namespace='accounts')),
    re_path(r'^about/', include('about.urls' ,namespace='about-us')),
    re_path(r'^', include('product.urls')),
    re_path(r'^category/', include('category.urls')),
    re_path(r'^contact/', include('contact.urls')),
    re_path(r'^feedback', include('feedback.urls')),
    re_path(r'^search/', include('search.urls')),
    re_path(r'^tag/', include('tag.urls')),
    re_path(r'^team/', include('team.urls')),
    re_path(r'^social-auth/', include('social_django.urls', namespace='social')),
    re_path(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='frontend/accounts/login.html'), name='login'),
    re_path(r'^accounts/logout/$', auth_views.LogoutView.as_view(), name='logout'),
    re_path(r'^accounts/reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='frontend/accounts/password_reset.html',
            html_email_template_name='frontend/accounts/password_reset_email.html',
            email_template_name='frontend/accounts/password_reset_email.html',
            subject_template_name='frontend/accounts/password_reset_subject.txt'
        ),
        name='password_reset'),
    re_path(r'^accounts/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='frontend/accounts/password_reset_done.html'),
        name='password_reset_done'),
    re_path(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='frontend/accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),
    re_path(r'^accounts/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='frontend/accounts/password_reset_complete.html'),
        name='password_reset_complete'),
    re_path(r'^settings/password/done/$',
        auth_views.PasswordChangeDoneView.as_view(template_name='frontend/accounts/password_change_done.html'),
        name='password_change_done'),


    # re_path(r'^.*\.*', views.pages, name='pages'),   

]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

product/urls.py
from .import views
from django.urls import re_path, path
from django.conf import settings
from django.conf.urls.static import static


app_name = 'product'

urlpatterns = [
    path('', views.product_category_list, name="product_and_category"),
    # re_path(r'^carbon/(?P<slug>[-\w]+)/$', views.product_category_list, name='detail_by_category_slug'),
    re_path(r'^all_product/', views.all_product_view, name = "all_product"),
    re_path(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]+)/(?P<day>[0-9]+)/(?P<slug>[\w-]+)/$', views.ProductDetailView.as_view(), name = 'detail'),
    path('mail/newsletter/unsubscribe/<str:token>', views.unsubscrib_redirect_view, name = "unsubscribe_redirect"),
   
    # re_path(r'^mail/newsletter/unsubscribe/(?P<token>[0-9A-Za-z].[0-9A-Za-z].[0-9A-Za-z])', views.unsubscrib_redirect_view, name = "unsubscribe_redirect"),
    # [A-Za-z0-9.-]

]


if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
   

users/urls.py
from .import views
from django.urls import re_path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'user'

urlpatterns = [

    re_path(r'^create/', views.ProfileView.as_view(), name='user-create'),
    re_path(r'^list/', views.UserListView.as_view(), name = 'user-list'), 
    re_path(r'^(?P<pk>[-\w]+)/delete/', views.DeleteUserView.as_view(), name = 'user-delete'),
    re_path(r'^edit/(?P<pk>[-\d]+)/$', views.ProfileUpdateView.as_view(), name='user-update'),
    re_path(r'^password-change/', views.ChangePasswordView.as_view(), name='password_change'),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.core.validators import validate_email
from painless.models.validations import validate_phone_number



class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)
    

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
            

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, validators = [validate_email])
    mobile = models.CharField(max_length = 12, validators= [validate_phone_number])
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    class Meta:
        verbose_name = "user"
        verbose_name_plural = "users"

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email



accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
User = get_user_model()


class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

accounts/views.py
from django.contrib.auth import authenticate, login as auth_login
from django.shortcuts import render, redirect
from .forms import SignUpForm


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(email=email, password=raw_password)
            auth_login(request, user)
            return redirect('product:product_and_category')
    else:
        form = SignUpForm()
    return render(request, 'frontend/accounts/register.html', {'form': form, 'title':"signup", "segment":"signup"})







templates/frontend/accounts/login.html
{% extends 'frontend/shared/index.html' %}
{% load static %}
{% block content %}
{% include 'frontend/partials/_header.html' %}
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center">
            <ol>
                <li><a href="{% url 'product:product_and_category' %}">Home</a></li>
                <li>Login</li>
            </ol>
        </div>

    </div>
</section>
<section>
    <div class="container-fluid p-0">
        <div class="row">
            <div class="col-12">
                <div class="login-card">
                    <form class="theme-form login-form" method="post">
                    <h4>Login</h4>
                    <h6>Welcome back! Log in to your account.</h6>

                        <!-- <form action="" method="post"> -->
                        {% csrf_token %}
                        {% include 'dashboard/includes/form.html' %}
                        <div class="form-group">
                            <button class="btn btn-success btn-block" type="submit">Sign in</button>
                          </div>
                        <br>
                        <div class="form-group mt-4">
                            <div class="checkbox">
                                <input id="checkbox1" type="checkbox">
                                <label for="checkbox1">Remember password</label>
                            </div><a class="link" href="{% url 'password_reset' %}">Forgot password?</a>
                        </div>
                        
                        <div class="login-social-title">
                            <h5>Sign in</h5>
                        </div>
                        <div class="form-group">
                            <ul class="login-social">
                                <li><a href="{% url 'social:begin' 'google-oauth2' %}" target="_blank"><i
                                            class="bi bi-google"></i></a></li>

                            </ul>
                        </div>
                        <p>Don't have account?<a class="ms-2" href="{% url 'accounts:signup' %}">Create Account</a></p>
                    </form>

                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/frontend/accounts/password_change.html
{% extends 'frontend/shared/index.html' %}
{% block title %}Password Change{% endblock %}
{% load static %}
{% block content %}
{% include 'frontend/partials/_header.html' %}
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center">
            <ol>
                <li><a href="{% url 'product:product_and_category' %}">Home</a></li>
                <li>Password Change</li>
            </ol>
        </div>

    </div>
</section>
<section>
    <div class="container-fluid p-0">
        <div class="row">
            <div class="col-12">
                <div class="login-card">
                    <form class="theme-form login-form" method="post">
                    <h4>Password Change</h4>
                        {% csrf_token %}
                        {% include 'dashboard/includes/form.html' %}
                      
                        <div class="form-group">
                            <button class="btn btn-success btn-block" type="submit">update</button>
                          </div>
                        <br>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/frontend/accounts/password_change_done.html





{% extends 'frontend/shared/index.html' %}

{% load static %}
{% block content %}
{% include 'frontend/partials/_header.html' %}
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center">
            <ol>
                <li><a href="{% url 'product:product_and_category' %}">Home</a></li>
                <li>Signup</li>
            </ol>
        </div>

    </div>
</section>
<section>
    <div class="container-fluid p-0">
        <div class="row">
            <div class="col-12">
                <div class="login-card">
                    <h4>Password Change</h4>
                    <div class="alert alert-success" role="alert">
                        Your password has been successfully changed!
                    </div>
                        <div class="form-group">
                            <a class="btn btn-success btn-block" href="{% url 'login' %}" type="submit">Sign up</a>
                          </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/frontend/accounts/password_reset.html
{% extends 'frontend/shared/index.html' %}
{% block title %}Password Reset{% endblock %}
{% load static %}
{% block content %}
{% include 'frontend/partials/_header.html' %}
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center">
            <ol>
                <li><a href="{% url 'product:product_and_category' %}">Home</a></li>
                <li>password reset</li>
            </ol>
        </div>

    </div>
</section>
<section>
    <div class="container-fluid p-0">
        <div class="row">
            <div class="col-12">
                <div class="login-card">
                    <form class="theme-form login-form" method="post">
                    <h4>Password reset</h4>
                    <h6>Welcome back! reset to your password.</h6>

                        {% csrf_token %}
                        {% include 'dashboard/includes/form.html' %}
                        <div class="col-lg-8 col-md-6 col-sm-6">
                            <small class="form group">
                                <a  href="{% url 'login' %}">Sign in</a>
                            </small>
                        </div>
                        <div class="col-lg-8 col-md-6 col-sm-6">
                            <small class="form-group">
                                 have you made an account?
                                <a class="font-q" href="{% url 'accounts:signup' %}">Sign Up</a>
                            </small>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-success btn-block" type="submit">Reset</button>
                          </div>
                        <br>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/frontend/accounts/password_reset_complete.html




{% extends 'frontend/shared/index.html' %}
{% block title %}Password Reset Complete{% endblock %}
{% load static %}
{% block content %}
{% include 'frontend/partials/_header.html' %}
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center">
            <ol>
                <li><a href="{% url 'product:product_and_category' %}">Home</a></li>
                <li>Password Reset Complete</li>
            </ol>
        </div>

    </div>
</section>
<section>
    <div class="container-fluid p-0">
        <div class="row">
            <div class="col-12">
                <div class="login-card">
             
                    <h4>Password Reset Complete</h4>
                    <div class="alert alert-success" role="alert">
                        You have successfully changed your password! You can now log in.
                    </div>

                        
                        <div class="col-lg-8 col-md-6 col-sm-6">
                            <small class="form group">
                                <a  class = "btn btn-success btn-block" href="{% url 'login' %}">Sign in</a>
                            </small>
                        </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/frontend/accounts/password_reset_confirm.html






{% extends 'frontend/shared/index.html' %}
{% block title %}Password Reset Confirm{% endblock %}
{% load static %}
{% block content %}
{% include 'frontend/partials/_header.html' %}
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center">
            <ol>
                <li><a href="{% url 'product:product_and_category' %}">Home</a></li>
                <li>Password Reset Confirm</li>
            </ol>
        </div>

    </div>
</section>
<section>
    <div class="container-fluid p-0">
        <div class="row">
            <div class="col-12">
                <div class="login-card">
                  {% if validlink %}
                    <form class="theme-form login-form" method="post">
                    <h4>Password Reset Confirm</h4>
                  
          <div class="alert alert-danger" role="alert">
            It looks like you clicked on an invalid password reset link. Please try again.
          </div>

                        {% csrf_token %}
                        {% include 'dashboard/includes/form.html' %}
                       
                        <div class="form-group">
                          <button type ="submit" class="btn btn-success btn-block">Change Password</button>
                        </div>
                    </form>
                    {% else %}
                    <div class="form-group">
                      <a href="{% url 'password_reset' %}" class="btn btn-success btn-block">Request a new password reset link</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/frontend/accounts/password_reset_done.html




{% extends 'frontend/shared/index.html' %}
{% block title %}Password Reset Done{% endblock %}
{% load static %}
{% block content %}
{% include 'frontend/partials/_header.html' %}
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center">
            <ol>
                <li><a href="{% url 'product:product_and_category' %}">Home</a></li>
                <li>Password Reset Done</li>
            </ol>
        </div>

    </div>
</section>
<section>
    <div class="container-fluid p-0">
        <div class="row">
            <div class="col-12">
                <div class="login-card">
                    <form class="theme-form login-form" method="post">
                    <div class="alert alert-success" role="alert"> <h6>Check your email to reset your password. If you do not receive it within 1 minute, please check your spam folder.
                      do !</h6></div>
                        <div class="col-lg-8 col-md-6 col-sm-6">
                            <small class="form group">
                                <a  class = "btn btn-success btn-block" href="{% url 'login' %}">Sign in</a>
                            </small>
                        </div>
                        <br>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/frontend/accounts/password_reset_email.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>

<body>
    <div>
        Hi there,

        Someone requested a password reset for the email address {{ email }}.
        Follow the link below:
        {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

        If you forgot your username, your username: {{ user.username }}


        If you didn't click the link above, please copy and paste the URL
        Instead in a new browser window

        If you received this email in error, another user may have logged in
        Your email address was incorrect when trying to reset your password. If you don't do this
        Start the application, you don't need to do anything else and you can feel free
        Ignore this email

        Thanks,
    </div>
</body>

</html>

templates/frontend/accounts/profile.html
{% extends "frontend/shared/home.html" %}
{% load static %}
{% block body %}
{% include 'frontend/partials/_head.html' %}

<section class="user-area-all-style sign-up-area ptb-100">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="contact-form-action">
                    <div class="form-heading text-center">
                        <h3 class="form-title"> اطلاعات شخصی!</h3>
                    </div>
                
                    <form method="post" action="{% url 'user:user-update' user.pk %}" novalidate  enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'dashboard/includes/form.html' %}
                        
                        <div class="col-12">
                            <button class="default-btn btn-block btn-two" type="submit">
                               ویرایش
                            </button>
                        </div>
                </form>
            </div>
        </div>
    </div>
    </div>
</section>

{% endblock %}

templates/frontend/accounts/register.html
{% extends 'frontend/shared/index.html' %}

{% load static %}
{% block content %}
{% include 'frontend/partials/_header.html' %}
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center">
            <ol>
                <li><a href="{% url 'product:product_and_category' %}">Home</a></li>
                <li>Signup</li>
            </ol>
        </div>

    </div>
</section>
<section>
    <div class="container-fluid p-0">
        <div class="row">
            <div class="col-12">
                <div class="login-card">
                    <form class="theme-form login-form" method="post">
                    <h4>Signup</h4>
                    <h6>Welcome back! Sign up to your account.</h6>

                        {% csrf_token %}
                        {% include 'dashboard/includes/form.html' %}
                        <div class="form-group">
                            <button class="btn btn-success btn-block" type="submit">Sign up</button>
                          </div>
                        <br>
                      
                    </form>

                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}