about/urls.py
from django.urls import re_path
from about.views import AboutView



app_name = "about"

urlpatterns = [
    re_path(r'^', AboutView.as_view(), name = "about-carbon"), 
  
]

api/urls.py
from django.urls import re_path, include
from rest_framework import routers 
from api.views import NewsLetterView


router = routers.DefaultRouter()




urlpatterns = [
    re_path(r'^', include(router.urls)),
    re_path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    re_path(r'^newsletter/',NewsLetterView.as_view(), name = "subscribe"),

    
]

config/urls.py
from django.contrib import admin
from django.urls import re_path, include,path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views



urlpatterns = [
    # re_path(r'^', views.home),
    path(r'admin/', admin.site.urls),
    re_path(r'^accounts/', include('accounts.urls',namespace='accounts')),
    re_path(r'^about/', include('about.urls' ,namespace='about-us')),
    re_path(r'^', include('product.urls')),
    re_path(r'^category/', include('category.urls')),
    re_path(r'^contact/', include('contact.urls')),
    re_path(r'^feedback', include('feedback.urls')),
    re_path(r'^search/', include('search.urls')),
    re_path(r'^tag/', include('tag.urls')),
    re_path(r'^team/', include('team.urls')),
    re_path(r'^social-auth/', include('social_django.urls', namespace='social')),
    re_path(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='frontend/accounts/login.html'), name='login'),
    re_path(r'^accounts/logout/$', auth_views.LogoutView.as_view(), name='logout'),
    re_path(r'^accounts/reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='frontend/accounts/password_reset.html',
            html_email_template_name='frontend/accounts/password_reset_email.html',
            email_template_name='frontend/accounts/password_reset_email.html',
            subject_template_name='frontend/accounts/password_reset_subject.txt'
        ),
        name='password_reset'),
    re_path(r'^accounts/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='frontend/accounts/password_reset_done.html'),
        name='password_reset_done'),
    re_path(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='frontend/accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),
    re_path(r'^accounts/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='frontend/accounts/password_reset_complete.html'),
        name='password_reset_complete'),
    re_path(r'^settings/password/done/$',
        auth_views.PasswordChangeDoneView.as_view(template_name='frontend/accounts/password_change_done.html'),
        name='password_change_done'),


    # re_path(r'^.*\.*', views.pages, name='pages'),   

]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/urls.py
from django.urls import re_path
from .import views
from config import settings
from django.conf.urls.static import static

app_name = 'contact'

urlpatterns = [
    re_path(r'^list/', views.ListContactView.as_view(), name = 'contact-list'), 
    re_path(r'^create/', views.CreateContactView.as_view(), name = 'contact-create'), 
    re_path(r'^(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/delete/', views.DeleteContactView.as_view(), name = 'delete'),
    re_path(r'^(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/show/', views.ContactShowView.as_view(), name='show'),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

product/urls.py
from .import views
from django.urls import re_path, path
from django.conf import settings
from django.conf.urls.static import static


app_name = 'product'

urlpatterns = [
    path('', views.product_category_list, name="product_and_category"),
    # re_path(r'^carbon/(?P<slug>[-\w]+)/$', views.product_category_list, name='detail_by_category_slug'),
    re_path(r'^all_product/', views.all_product_view, name = "all_product"),
    re_path(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]+)/(?P<day>[0-9]+)/(?P<slug>[\w-]+)/$', views.ProductDetailView.as_view(), name = 'detail'),
    path('mail/newsletter/unsubscribe/<str:token>', views.unsubscrib_redirect_view, name = "unsubscribe_redirect"),
   
    # re_path(r'^mail/newsletter/unsubscribe/(?P<token>[0-9A-Za-z].[0-9A-Za-z].[0-9A-Za-z])', views.unsubscrib_redirect_view, name = "unsubscribe_redirect"),
    # [A-Za-z0-9.-]

]


if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
   

team/urls.py
from django.urls import re_path
from team.views import  TeamView



app_name = "team"

urlpatterns = [
    re_path(r'^', TeamView.as_view(), name = "team-carbon"), 
  
]

slider/models.py
from django.db import models
from painless.models.mixins import OrganizedMixin
from painless.models.managers import PostPublishedManager
from ckeditor.fields import RichTextField



class Slider(OrganizedMixin):
    summary = models.CharField(max_length = 128)
    banner = models.ImageField(upload_to = 'slider/%Y/%m/%d', null = True, blank = True)
    content = RichTextField(blank=True,null=True)
    
    condition = PostPublishedManager()

    class Meta:
        verbose_name = "slider"
        verbose_name_plural = "sliders"
     
    def __str__(self):
        return self.title

    
    

templates/frontend/includes/_footer.html
        <!-- ======= Footer ======= -->
        <footer id="footer">

            <div class="footer-top">
              <div class="container">
                <div class="row">
        
                  <div class="col-lg-3 col-md-6 footer-contact">
                    <h3>jiZeng</h3>
                    <p>
                     Pm 401,Unit715 <br>
                      Jiangdong St, Yiwu City, Zhejiang Province<br>
                       <br><br>
                      <strong>Phone:</strong> +86 1582 183 9875<br>
                      <strong>Email:</strong> diana@top-carbon.com  graphite.jessiezxr518@gmail.com<br>
                    </p>
                  </div>
        
                  <div class="col-lg-2 col-md-6 footer-links">
                    <h4>Useful Links</h4>
                    <ul>
                      <li><i class="bi bi-chevron-right"></i> <a href="#">Home</a></li>
                      <li><i class="bi bi-chevron-right"></i> <a href="#">About us</a></li>
                      <li><i class="bi bi-chevron-right"></i></i> <a href="#">Services</a></li>
                      <li><i class="bi bi-chevron-right"></i></i> <a href="#">Terms of service</a></li>
                      <li><i class="bi bi-chevron-right"></i></i> <a href="#">Privacy policy</a></li>
                    </ul>
                  </div>
        
                  <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Our Services</h4>
                    <ul>
                      <li><i class="bi bi-chevron-right"></i> <a href="#">Web Design</a></li>
                      <li><i class="bi bi-chevron-right"></i> <a href="#">Web Development</a></li>
                      <li><i class="bi bi-chevron-right"></i> <a href="#">Product Management</a></li>
                      <li><i class="bi bi-chevron-right"></i> <a href="#">Marketing</a></li>
                      <li><i class="bi bi-chevron-right"></i> <a href="#">Graphic Design</a></li>
                    </ul>
                  </div>
        
                  <div class="col-lg-4 col-md-6 footer-newsletter">
                    <h4>Join Our Newsletter</h4>
                    <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
                    {% include 'frontend/partials/_subscribe.html' %}
                 
                  </div>
        
                </div>
              </div>
            </div>
        
             <div class="container d-md-flex py-4"> 
        
               <div class="me-md-auto text-center text-md-start"> 
                 <div class="copyright">
                  &copy; Copyright <strong><span>Carbon</span></strong>. All Rights Reserved
                </div> 
                <div class="credits">
                 
                   Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                </div> 
              </div> 
  
               <div class="social-links text-center text-md-right pt-3 pt-md-0 py-4">
                <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                <a href="#" class="youtube"><i class="bi bi-youtube"></i></a>
              </div>
            </div> 
          </footer>  
  
          <!-- End Footer-->
        
        
     <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
  

templates/frontend/includes/_head.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{{ segment|capfirst }}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/frontend/img/favicon.png' %}" rel="icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor {% static '' %}CSS Files -->
  <link href="{% static '/assets/frontend/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static '/assets/frontend/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static '/assets/frontend/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static '/assets/frontend/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static '/assets/frontend/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static '/assets/frontend/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static '/assets/frontend/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static '/assets/frontend/css/style.css' %}" rel="stylesheet">
  <link href="{% static '/assets/frontend/css/product-details.css' %}" rel="stylesheet">
  <link href="{% static '/assets/frontend/css/login.css' %}" rel="stylesheet">

{% block style %}{% endblock %}
</head>

templates/frontend/includes/_header.html
        
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container">
      <div class="header-container d-flex align-items-center justify-content-between">
        <div class="logo">
          <h1 class="text-light"><a href="{% url 'product:product_and_category' %}"><span>jiZeng</span></a></h1>
        </div>
       
        <nav id="navbar" class="navbar">
          <ul>
            <li><a class="nav-link scrollto {% if request.resolver_match.url_name == 'product_and_category' %}active{% endif %}" href="{% url 'product:product_and_category' %}"> Home</a></li>
            <li><a class="nav-link scrollto {% if request.resolver_match.url_name == 'about-carbon' %}active{% endif %}" href="{% url 'about:about-carbon' %}">About</a></li>
            <li><a class="nav-link scrollto {% if request.resolver_match.url_name == 'contact-create' %}active{% endif %}" href="{% url 'contact:contact-create' %}">Contact</a></li>
            <li><a class="nav-link scrollto {% if request.resolver_match.url_name == 'team-carbon' %}active{%endif%}" href="{% url 'team:team-carbon' %}">Team</a></li>
            
            <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">PRODUCTS</a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a href="{% url 'product:all_product' %}">products</a></li>
                {% for category in categories %}
                {% if category.is_parent %}
                <li class="dropdown"><a href="{{ category.products_base_on_category }}">{{ category.title }}<i class="bi bi-caret-right-fill"></i></a>
                  {% for subcategory in category.children %}
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{{ subcategory.get_absolute_url }}">{{ subcategory.title }}</a>
                      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for postcat in subcategory.products.all %}
                        <li><a class="dropdown-item" href="{{ postcat.get_absolute_url }}">{{ subcategory.title }}</a></li>
                        {% endfor %}
                      </ul>
                    </li>
                  </ul>
                  {% endfor %}
                </li>
                {% endif %}
                {% endfor %}
              </ul>
            </li>
            {% if user.is_authenticated %}
            {% if user.is_superuser %}
            <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Account</a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="nav-link" href="/admin/"> <i class="bi bi-person-fill"></i> Admin</a></li>
                <li><a class="nav-link" href="{% url 'logout' %}"> <i class="bi bi-box-arrow-right"></i> Sign Out</a></li>
              </ul>
            </li>
              {% endif %}
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">
                    <i class="bi bi-person-fill"></i>
                    <span>
                      Sign in
                    </span>
                  </a>
                </li>
            {% endif %}
            <form class="form-inline justify-content-center" method = "GET" action="/search/">
              <input class="form-control" name="q" id="q" placeholder="     Search ..." type="text">
              <button class="btn m-5 my-sm-0 nav_search-btn" type="submit">
                <i class="bi bi-search"></i>
              </button>
            </form>
          </ul>
          <i class="bi bi-list mobile-nav-toggle"></i>
        </nav>
      </div>
    </div>
  </header>

templates/frontend/includes/_pagination.html
<div class="col-lg-12">
    <div class="page-navigation-area">
        {% if page_obj %}
        {% if page_obj.has_other_pages %}
        <nav>
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link page-links" href="?page={{ page_obj.previous_page_number }}">
                        <i class="bx bx-chevrons-right"></i>
                    </a>
                </li>
                {% endif %}
                {% for page_number in page_obj.paginator.page_range %}
                {% if page_obj.number == page_number %}
                <li class="page-item active">
                    <a class="page-link" href="#">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item active">
                    <a href="?page={{ page_number }}" class="btn btn-outline-primary">
                        {{ page_number }}
                    </a>
                </li>
                {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        <i class="bx bx-chevrons-left"></i>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
        {% else %}
        <p>No items found.</p>
        {% endif %}
    </div>
</div>

templates/frontend/includes/_script.html
{% load static %}
{% block script %}
  <script src="{% static '/assets/frontend/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static '/assets/frontend/vendor/aos/aos.js' %}"></script>
  <script src="{% static '/assets/frontend/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static '/assets/frontend/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static '/assets/frontend/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static '/assets/frontend/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static '/assets/frontend/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static '/assets/frontend/js/main.js' %}"></script>
  <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

  {% endblock %}
</body>
</html>

templates/frontend/includes/_slider.html
<div id="carouselExampleDark" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      {% for slider in sliders %}
      <div class="carousel-item active" data-bs-interval="10000">
        <img src="{{ slider.banner.url }}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>{{ slider.summary }}</h5>
          <p>{{ slider.content|striptags|safe }}</p>
        </div>
      </div>
      {% endfor %}
    
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>